# Copyright 2021 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# ---------stop all multicloud services ---------
- name: stop all services in the namespace soda-multi-cloud
  shell: "{{ item }}"
  args:
    chdir: "{{ gelato_work_dir }}/multi-cloud/K8s"
  with_items:
    - bash "k8s-delete-namespace.sh"      
  become_user: ubuntu
  ignore_errors: yes
  when: install_gelato_ha_from == "release" or install_gelato_ha_from == "container"

# ---------delete the multi-cloud folder in /opt/opensds-gelato ---------
- name: Clean artifact path ub /opt/opensds-gelato...
  file:
    state: absent
    path: "{{ gelato_work_dir }}/multi-cloud/"
  ignore_error: yes
  become: yes
  when: install_gelato_ha_from == "release" or install_gelato_ha_from == "container"
